export const CREATE_WORK = "CREATE_WORK";
export const CREATE_WORK_SUCCESS = "CREATE_WORK_SUCCESS";
export const CREATE_WORK_FAIL = "CREATE_WORK_FAIL";

export const GET_LIST_WORK = "GET_LIST_WORK";
export const GET_LIST_WORK_SUCCESS = "GET_LIST_WORK_SUCCESS";
export const GET_LIST_WORK_FAIL = "GET_LIST_WORK_FAIL";

export const DELETE_WORK = "DELETE_WORK";
export const DELETE_WORK_SUCCESS = "DELETE_WORK_SUCCESS";
export const DELETE_WORK_FAIL = "DELETE_WORK_FAIL";

export const EDIT_WORK = "EDIT_WORK";
export const EDIT_WORK_SUCCESS = "EDIT_WORK_SUCCESS";
export const EDIT_WORK_FAIL = "EDIT_WORK_FAIL";
